public class HBT_Constantes {
    //Constantes parametros examenes
    public static final String PARAM_EXAMEN_NAME = 'Examen';
    public static final String PARAM_HV_NAME = 'Hoja de vida';
    public static final String PARAM_ANTECEDENTE_NAME = 'Antecedente';
    public static final String PARAM_GENERAL_NAME = 'General';
    public static final String PARAM_GENERAL_NOTIFICACION = 'Notificación sin ingreso';
    public static final String PARAM_GENERAL_INACTIVACION = 'Inactivación sin ingreso';
    public static final String PARAM_GENERAL_VENCIMIENTOCERTIFICACION = 'Vencimiento certificación';
    public static final String PARAM_HV_DILIGENCIAMIENTO = 'Dias diligenciamiento';
    public static final String PARAM_HV_ACTUALIZACION = 'Dias actualización';
    public static final String PARAM_EXAMEN_DIASPRESENTACION = 'Dias presentación examen';
    public static final String PARAM_EXAMEN_DIASREPROGRAMAR = 'Dias reprogramar examen';
    public static final String PARAM_EXAMEN_DIASVENCIMIENTO = 'Dias vencimiento examen';
    public static final String PARAM_EXAMEN_HORASCONFIRMACION = 'Horas confirmación lista de espera';
    public static final String PARAM_EXAMEN_VALORIMPUESTO = 'Valor impuesto';
    public static final String PARAM_ANT_DIASVENCIMIENTO = 'Dias vencimiento antecedente';
    public static final String PARAM_ANT_VALORIMPUESTO = 'Valor impuesto';
    //Constantes Generales
    public static final String GENERAL_ESTADO_ACTIVO = 'Activo';
    public static final String GENERAL_ESTADO_INACTIVO = 'Inactivo';
    public static final String GENERAL_PERFIL_PROFESIONAL = 'Profesional';
    //Constantes Profesional
    public static final String PROFESIONAL_TIPODOC_CEDULA = '1';
    //Constantes relacionadas con salas
    public static final String SALA_TIPOSALA_VIRTUAL = 'Virtual';
    public static final String SALA_TIPOSALA_FISICA = 'Fisica';
    public static final String SALA_TIPOPARAMETRIZACION_PARAMETRIZACION = 'Parametrización de disponibilidad';
    //Constantes terminos y condiciones
     public static final String TYC_TIPO_HOJAVIDA = 'Hoja de vida';
    public static final String TYC_TIPO_EXAMEN = 'Examen';
    //Constantes de entidades
     public static final String ENTIDAD_TIPOMERCADO_DIVISA = 'Divisas';
    //Constantes de examenes
    public static final String EXAMEN_ESTADO_PENDIENTE = 'Pendiente aprobación';
    public static final String EXAMEN_ESTADO_ACTIVO = 'Activo';
    public static final String EXAMEN_ESTADO_APROBADO = 'Aprobado';
    public static final String EXAMEN_ESTADO_REPROBADO = 'Reprobado';
    public static final String EXAMEN_ESTADO_PROGRAMADO = 'Programado';
    public static final String EXAMEN_ESTADO_PENDIENTE_PROGRAMAR = 'Pendiente por programar';
    public static final String EXAMEN_ESTADO_PENDIENTE_PRESENTAR = 'Pendiente por presentar';
    public static final String EXAMEN_ESTADO_NO_ASISTIO = 'No asistió';
    public static final String EXAMEN_ESTADO_NO_APROBADO = 'No aprobado';
    public static final String EXAMEN_ESTADO_PENDIENTE_PAGAR = 'Pendiente por pagar';
    public static final String EXAMEN_ESTADO_REGISTRADO = 'Registrado';
    public static final String EXAMEN_ESTADO_VENCIDO = 'Vencido';
    public static final String EXAMEN_ESTADO_PAGO_RECHAZADO = 'Pago rechazado';
    public static final String EXAMEN_ESTADO_PAGADO = 'Pagado';


    //Constantes de antecedentes
    public static final String ANT_ESTADO_NUEVO = 'Nuevo';
    public static final String ANT_ESTADO_ACTIVO = 'Activo';
    public static final String ANT_ESTADO_INACTIVO = 'Inactivo';
    public static final String ANT_ESTADO_PENDIENTE = 'Pendiente aprobación';

}